/**
 * cityAssets.js
 * Sprite manifest + image loader for the iso city view.
 *
 * Building sprites: rig-rendered grit set + AI-generated set (ADR 0021/0024).
 * Each building sprite includes its own ground block and is drawn bottom-anchored
 * over the procedural city ground (`js/ui/city/cityGround.js`).
 */

const G = 'assets/tiles/buildings/grit';
const A = 'assets/tiles/buildings/ai';

/**
 * Grit building set, rig-rendered to the tile grid from CC0 packs (Quaternius
 * Ultimate Fantasy RTS / Farm Buildings / Zombie Apocalypse, Kenney Survival Kit) —
 * ADR 0009/0010.
 * Level-keyed evolution sprites; buckets map building level → {1,2,3+}. Trimmed to
 * content bbox at a shared scale so relative sizes are authored, not normalised.
 * Covers all 20 types; a type absent here falls back to a colored diamond.
 */
export const GRIT_BUILDING_MAP = {
  townhall:          { 1: `${G}/townhall_L1.png`,          2: `${G}/townhall_L2.png`,          3: `${G}/townhall_L3.png` },
  heroquarters:      { 1: `${G}/heroquarters_L1.png`,      2: `${G}/heroquarters_L2.png`,      3: `${G}/heroquarters_L3.png` },
  barracks:          { 1: `${G}/barracks_L1.png`,          2: `${G}/barracks_L2.png`,          3: `${G}/barracks_L3.png` },
  construction_hall: { 1: `${G}/construction_hall_L1.png`, 2: `${G}/construction_hall_L2.png`, 3: `${G}/construction_hall_L3.png` },
  lumbermill:        { 1: `${G}/lumbermill_L1.png`,        2: `${G}/lumbermill_L2.png`,        3: `${G}/lumbermill_L3.png` },
  storehouse:        { 1: `${G}/storehouse_L1.png`,        2: `${G}/storehouse_L2.png`,        3: `${G}/storehouse_L3.png` },
  cafeteria:         { 1: `${G}/cafeteria_L1.png`,         2: `${G}/cafeteria_L2.png`,         3: `${G}/cafeteria_L3.png` },
  mine:              { 1: `${G}/mine_L1.png`,              2: `${G}/mine_L2.png`,              3: `${G}/mine_L3.png` },
  quarry:            { 1: `${G}/quarry_L1.png`,            2: `${G}/quarry_L2.png`,            3: `${G}/quarry_L3.png` },
  bank:              { 1: `${G}/bank_L1.png`,              2: `${G}/bank_L2.png`,              3: `${G}/bank_L3.png` },
  farm:              { 1: `${G}/farm_L1.png`,              2: `${G}/farm_L2.png`,              3: `${G}/farm_L3.png` },
  workshop:          { 1: `${G}/workshop_L1.png`,          2: `${G}/workshop_L2.png`,          3: `${G}/workshop_L3.png` },
  archeryrange:      { 1: `${G}/archeryrange_L1.png`,      2: `${G}/archeryrange_L2.png`,      3: `${G}/archeryrange_L3.png` },
  house:             { 1: `${G}/house_L1.png`,             2: `${G}/house_L2.png`,             3: `${G}/house_L3.png` },
  cavalrystable:     { 1: `${G}/cavalrystable_L1.png`,     2: `${G}/cavalrystable_L2.png`,     3: `${G}/cavalrystable_L3.png` },
  infantryhall:      { 1: `${G}/infantryhall_L1.png`,      2: `${G}/infantryhall_L2.png`,      3: `${G}/infantryhall_L3.png` },
  magictower:        { 1: `${G}/magictower_L1.png`,        2: `${G}/magictower_L2.png`,        3: `${G}/magictower_L3.png` },
  rallypoint:        { 1: `${G}/rallypoint_L1.png`,        2: `${G}/rallypoint_L2.png`,        3: `${G}/rallypoint_L3.png` },
  well:              { 1: `${G}/well_L1.png`,              2: `${G}/well_L2.png`,              3: `${G}/well_L3.png` },
  siegeworkshop:     { 1: `${G}/siegeworkshop_L1.png`,     2: `${G}/siegeworkshop_L2.png`,     3: `${G}/siegeworkshop_L3.png` },
};

/**
 * AI-generated building set (ADR 0024), stage-keyed like the grit map. Sprites +
 * per-sprite ground anchors live in `assets/tiles/buildings/ai/` and are
 * regenerated by `assestProcessing/ingest.py`. A type present here takes
 * precedence over its grit/legacy art **only in a dev AI session** (see
 * `variantKey`/`aiEnabled`); grit is the default for everyone. Add a type by wiring
 * its stages here once its sprites land. Levels beyond a type's highest stage
 * clamp to that stage.
 */
export const AI_BUILDING_MAP = {
  townhall: { 1: `${A}/townhall_S1.png`, 2: `${A}/townhall_S2.png`, 3: `${A}/townhall_S3.png`, 4: `${A}/townhall_S4.png` },
};

function highestBucket(map, id, fallback) {
  const buckets = map[id];
  return buckets ? Math.max(...Object.keys(buckets).map(Number)) : fallback;
}

/** Building level → grit sprite bucket, clamped to that building's own highest
 *  available bucket (types top out at whatever levels their art ships — 3 today).
 *  A flat global clamp would silently fall back to bucket 1 art for any type once
 *  its real level exceeds the clamp — this keeps it "best available". */
export function gritBucket(id, level) {
  return Math.max(1, Math.min(highestBucket(GRIT_BUILDING_MAP, id, 3), level | 0));
}

/** Building level → AI sprite stage, clamped to that type's highest stage. */
export function stageBucket(id, level) {
  return Math.max(1, Math.min(highestBucket(AI_BUILDING_MAP, id, 1), level | 0));
}

/** Normalise a manifest anchor to `{ax, ay, s, r, k}`: scale (default 1),
 *  rotation r in degrees and horizontal-shear k in degrees (both default 0). */
export function normalizeAnchor(a) {
  return {
    ax: a.ax,
    ay: a.ay,
    s: Number.isFinite(a.s) ? a.s : 1,
    r: Number.isFinite(a.r) ? a.r : 0,
    k: Number.isFinite(a.k) ? a.k : 0,
  };
}

export class CityAssets {
  constructor() {
    this._images = new Map();   // key → HTMLImageElement
    this._gray   = new Map();   // building key → offscreen grayscale canvas
    this._pad    = new Map();   // building key → transparent px below content
    this._anchor = new Map();   // building key → {ax, ay, s?} ground-contact centre (sprite px)
    this._devAnchor = new Map();// building key → live dev-nudge override (DevAnchorNudger)
    this.ready   = false;
    this.aiEnabled = typeof location !== 'undefined'
      && new URLSearchParams(location.search).has('ai');
  }

  /** Dev-only: route resolvable slots through the AI set instead of grit. Grit is the
   *  default for everyone; a `?ai` boot or the dev sprite-source toggle flips this. */
  setAiSprites(on) { this.aiEnabled = !!on; }

  /** Load every sprite; resolves even if some fail (renderer falls back per-tile). */
  async load() {
    const mapEntries = (map, prefix) =>
      Object.entries(map).flatMap(([id, levels]) =>
        Object.entries(levels).map(([lvl, src]) => [`${prefix}:${id}:${lvl}`, src]));
    const aiEntries = mapEntries(AI_BUILDING_MAP, 'a');
    const gritEntries = mapEntries(GRIT_BUILDING_MAP, 'b');
    const entries = [
      ...gritEntries,
      ...aiEntries,
    ];
    await Promise.all(entries.map(async ([key, src]) => {
      const img = new Image();
      img.src = src;
      try {
        await img.decode();
        this._images.set(key, img);
      } catch {
        // Missing sprite → renderer draws a colored fallback diamond.
      }
    }));
    await this._loadAnchors([`${G}/_anchors.json`], gritEntries);
    await this._loadAnchors([`${A}/_anchors.json`, `${A}/_anchor_overrides.json`], aiEntries);
    this._prerenderGrayscale();
    this.ready = true;
  }

  /**
   * Resolve a building type+level to its best available sprite key: grit level art,
   * then grit L1 — with AI stage art taking precedence only when `aiEnabled` (dev,
   * ADR 0024). One resolver so draw, grayscale, grade, anchor and pad cannot pick
   * different sprites for a slot.
   */
  variantKey(id, level = 0) {
    if (this.aiEnabled && level > 0 && AI_BUILDING_MAP[id]) {
      const k = `a:${id}:${stageBucket(id, level)}`;
      if (this._images.has(k)) return k;
    }
    if (GRIT_BUILDING_MAP[id]) {
      const k = `b:${id}:${gritBucket(id, level)}`;
      if (this._images.has(k)) return k;
    }
    return `b:${id}:1`;
  }

  /**
   * Per-sprite ground-contact centre exported by the render rig / ingest pipeline
   * (ADR 0022/0024). The renderer seats this point on the plot centre, so a
   * building sits centred on its footprint at any size or level. Keyed by sprite
   * filename in each set's `_anchors.json`; missing → bottom-centre fallback.
   */
  async _loadAnchors(urls, entries) {
    const manifest = {};
    for (const url of urls) {
      try {
        const res = await fetch(url, { cache: 'no-store' });
        if (res.ok) Object.assign(manifest, await res.json());
      } catch { /* later urls (overrides) merge over earlier; missing is fine */ }
    }
    for (const [key, src] of entries) {
      const a = manifest[src.slice(src.lastIndexOf('/') + 1)];
      if (a && Number.isFinite(a.ax) && Number.isFinite(a.ay)) this._anchor.set(key, a);
    }
  }

  /** Resolve a building sprite: grit level art → grit L1 (AI stage art first when dev-enabled). */
  building(id, level = 0) {
    return this._images.get(this.variantKey(id, level)) ?? null;
  }

  /** Ground-contact centre + scale of a sprite in its own px; a live dev nudge
   *  (DevAnchorNudger) wins, then the manifest, then a bottom-centre fallback. */
  anchor(id, level = 0) {
    const key = this.variantKey(id, level);
    const dev = this._devAnchor.get(key);
    if (dev) return dev;
    const a = this._anchor.get(key);
    if (a) return normalizeAnchor(a);
    const img = this._images.get(key);
    return { ax: (img?.width ?? 0) / 2, ay: img?.height ?? 0, s: 1, r: 0, k: 0 };
  }

  /** Live dev-nudge override (`?dev` only) — checked first by `anchor()`. */
  setDevAnchor(id, level, a) {
    this._devAnchor.set(this.variantKey(id, level), normalizeAnchor(a));
  }

  clearDevAnchor(id, level) {
    this._devAnchor.delete(this.variantKey(id, level));
  }

  /** Sprite filename backing this type+level (the `_anchor_overrides.json` key). */
  variantFile(id, level = 0) {
    const [set, kid, bucket] = this.variantKey(id, level).split(':');
    const map = set === 'a' ? AI_BUILDING_MAP : GRIT_BUILDING_MAP;
    const src = map[kid]?.[bucket];
    return src ? src.slice(src.lastIndexOf('/') + 1) : null;
  }

  /** Transparent rows under a sprite's visible content (draw anchors subtract this). */
  bottomPad(id, level = 0) {
    return this._pad.get(this.variantKey(id, level)) ?? 0;
  }

  buildingGray(id, level = 0) {
    return this._gray.get(this.variantKey(id, level)) ?? null;
  }

  /** Every loaded building-sprite key — AI (`a:*`), grit + legacy (`b:*`). */
  buildingVariantKeys() {
    return [...this._images.keys()].filter((k) => k.startsWith('b:') || k.startsWith('a:'));
  }

  imageByKey(key) { return this._images.get(key) ?? null; }
  grayByKey(key)  { return this._gray.get(key) ?? null; }

  /** Pre-render grayscale building variants once (locked slots) — avoids per-frame ctx.filter. */
  _prerenderGrayscale() {
    for (const key of this.buildingVariantKeys()) {
      const img = this._images.get(key);
      const cv = document.createElement('canvas');
      cv.width = img.width;
      cv.height = img.height;
      const cx = cv.getContext('2d');
      cx.drawImage(img, 0, 0);
      this._pad.set(key, this._measureBottomPad(cx, cv.width, cv.height));
      cx.filter = 'grayscale(1) brightness(0.55)';
      cx.clearRect(0, 0, cv.width, cv.height);
      cx.drawImage(img, 0, 0);
      this._gray.set(key, cv);
    }
  }

  _measureBottomPad(cx, w, h) {
    const a = cx.getImageData(0, 0, w, h).data;
    for (let y = h - 1; y >= 0; y--) {
      for (let x = 0; x < w; x++) {
        if (a[(y * w + x) * 4 + 3] > 8) return h - 1 - y;
      }
    }
    return 0;
  }
}
